In [456]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [457]:
movies= pd.read_csv("/content/tmdb_5000_movies.csv")
credits= pd.read_csv("/content/tmdb_5000_credits.csv")
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [458]:
movies.shape

(4803, 20)

In [459]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [460]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [461]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [462]:
## To obtain a single dataframe

df= pd.concat([movies,credits],axis=1,)
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,title,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [463]:
df.shape

(4803, 24)

In [464]:
movies=movies.merge(credits,on="title")

In [465]:
movies.shape

(4809, 23)

In [466]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [467]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [468]:
# movies["original_language"].value_counts()

In [469]:
## genres, id, keywords, title, overview, cast,crew

movies= movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [470]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [471]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [472]:
movies.dropna(inplace=True)

In [473]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [474]:
movies.duplicated().sum()

0

In [475]:
movies["cast"]= movies["cast"].astype(object)

In [476]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [477]:
len(movies.genres)

4806

In [478]:
import ast ##nimp library
l=[]
def convert(obj):
  for i in obj:
    l.append(i['name'])
  return l

for i in range(len(movies.genres)):
  convert(ast.literal_eval(movies.iloc[i].genres))

In [479]:
print(l)

['Action', 'Adventure', 'Fantasy', 'Science Fiction', 'Adventure', 'Fantasy', 'Action', 'Action', 'Adventure', 'Crime', 'Action', 'Crime', 'Drama', 'Thriller', 'Action', 'Adventure', 'Science Fiction', 'Fantasy', 'Action', 'Adventure', 'Animation', 'Family', 'Action', 'Adventure', 'Science Fiction', 'Adventure', 'Fantasy', 'Family', 'Action', 'Adventure', 'Fantasy', 'Adventure', 'Fantasy', 'Action', 'Science Fiction', 'Adventure', 'Action', 'Thriller', 'Crime', 'Adventure', 'Fantasy', 'Action', 'Action', 'Adventure', 'Western', 'Action', 'Adventure', 'Fantasy', 'Science Fiction', 'Adventure', 'Family', 'Fantasy', 'Science Fiction', 'Action', 'Adventure', 'Adventure', 'Action', 'Fantasy', 'Action', 'Comedy', 'Science Fiction', 'Action', 'Adventure', 'Fantasy', 'Action', 'Adventure', 'Fantasy', 'Action', 'Adventure', 'Adventure', 'Fantasy', 'Adventure', 'Fantasy', 'Adventure', 'Drama', 'Action', 'Drama', 'Romance', 'Thriller', 'Adventure', 'Action', 'Science Fiction', 'Thriller', 'Action', 'Adventure', 'Science Fiction', 'Action', 'Adventure', 'Science Fiction', 'Thriller', 'Action', 'Adventure', 'Thriller', 'Action', 'Adventure', 'Fantasy', 'Action', 'Adventure', 'Science Fiction', 'Family', 'Fantasy', 'Adventure', 'Adventure', 'Action', 'Science Fiction', 'Thriller', 'Animation', 'Family', 'Science Fiction', 'Action', 'Adventure', 'Science Fiction', 'Action', 'Adventure', 'Fantasy', 'Adventure', 'Family', 'Action', 'Adventure', 'Fantasy', 'Adventure', 'Action', 'Science Fiction', 'Animation', 'Family', 'Adventure', 'Comedy', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'Animation', 'Family', 'Comedy', 'Action', 'Science Fiction', 'Thriller', 'Action', 'Action', 'Drama', 'Horror', 'Science Fiction', 'Thriller', 'Action', 'Adventure', 'Fantasy', 'Science Fiction', 'Action', 'Adventure', 'Science Fiction', 'Action', 'Family', 'Fantasy', 'Drama', 'Romance', 'Adventure', 'Fantasy', 'Action', 'Romance', 'Action', 'Science Fiction', 'Adventure', 'Action', 'Science Fiction', 'Adventure', 'Adventure', 'Action', 'Adventure', 'Animation', 'Family', 'Animation', 'Adventure', 'Comedy', 'Family', 'Action', 'Fantasy', 'Action', 'Adventure', 'Science Fiction', 'Animation', 'Family', 'Action', 'Comedy', 'Crime', 'Thriller', 'Action', 'Adventure', 'Science Fiction', 'Animation', 'Drama', 'Science Fiction', 'Fantasy', 'Action', 'Adventure', 'Action', 'Adventure', 'Adventure', 'Family', 'Fantasy', 'Science Fiction', 'Drama', 'Action', 'Crime', 'Thriller', 'Animation', 'Comedy', 'Family', 'Adventure', 'Animation', 'Family', 'Adventure', 'Science Fiction', 'Action', 'Science Fiction', 'Adventure', 'Adventure', 'Drama', 'Family', 'Action', 'Adventure', 'Comedy', 'Science Fiction', 'Western', 'Adventure', 'Action', 'Fantasy', 'Action', 'Adventure', 'Crime', 'Fantasy', 'Science Fiction', 'Fantasy', 'Comedy', 'Family', 'Action', 'Science Fiction', 'Adventure', 'Action', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'Drama', 'Comedy', 'Animation', 'Family', 'Family', 'Adventure', 'Drama', 'Fantasy', 'Adventure', 'Action', 'Science Fiction', 'Adventure', 'Fantasy', 'Drama', 'Fantasy', 'Adventure', 'Action', 'Family', 'Romance', 'Science Fiction', 'Action', 'Drama', 'Thriller', 'Action', 'Adventure', 'Science Fiction', 'Romance', 'Drama', 'Action', 'Adventure', 'Fantasy', 'Action', 'Adventure', 'Science Fiction', 'Comedy', 'Adventure', 'Fantasy', 'Animation', 'Family', 'Adventure', 'Family', 'Mystery', 'Science Fiction', 'Adventure', 'Family', 'Animation', 'Action', 'Comedy', 'Family', 'Animation', 'Comedy', 'Adventure', 'Adventure', 'Animation', 'Family', 'Fantasy', 'Action', 'Adventure', 'Science Fiction', 'Fantasy', 'Adventure', 'Animation', 'Family', 'Action', 'Thriller', 'Science Fiction', 'Action', 'Science Fiction', 'Adventure', 'Adventure', 'Drama', 'Science Fiction', 'Action', 'Thriller', 'Science Fiction', 'Mystery', 'Adventure', 'Action', 'Adventure', 'Drama', 'Horror', 'Science Fiction', 'Adventure', 'Fantasy', 'Action', 'Action', 'Crime', 'Thriller', 'Fantasy', 'Drama', 'Thriller', 'Mystery', 'Romance', 'Action', 'Science Fiction', 'Adventure', 'Action', 'Adventure', 'Science Fiction', 'Fantasy', 'Adventure', 'Action', 'Comedy', 'Drama', 'Adventure', 'Action', 'Drama', 'Thriller', 'Fantasy', 'Fantasy', 'Adventure', 'Animation', 'Comedy', 'Family', 'Action', 'Adventure', 'Fantasy', 'Science Fiction', 'Action', 'Thriller', 'Adventure', 'Adventure', 'Family', 'Fantasy', 'History', 'Romance', 'War', 'Adventure', 'Science Fiction', 'Action', 'War', 'History', 'Action', 'Adventure', 'Drama', 'Romance', 'Adventure', 'Fantasy', 'Family', 'Mystery', 'Adventure', 'Fantasy', 'Family', 'Fantasy', 'Action', 'Drama', 'Horror', 'Action', 'Thriller', 'Science Fiction', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Animation', 'Comedy', 'Family', 'Fantasy', 'Action', 'Crime', 'Drama', 'Family', 'Animation', 'Adventure', 'Fantasy', 'Action', 'Comedy', 'Family', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'Animation', 'Adventure', 'Family', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'Action', 'Adventure', 'Fantasy', 'Action', 'Adventure', 'Science Fiction', 'Thriller', 'Thriller', 'Mystery', 'Adventure', 'Fantasy', 'Action', 'Animation', 'Family', 'Adventure', 'Comedy', 'Fantasy', 'Action', 'Adventure', 'Family', 'Comedy', 'Adventure', 'Comedy', 'Fantasy', 'Action', 'Adventure', 'Thriller', 'Drama', 'Horror', 'Thriller', 'Family', 'Animation', 'Adventure', 'Comedy', 'Animation', 'Family', 'Action', 'Adventure', 'Family', 'Fantasy', 'Adventure', 'Action', 'Thriller', 'Action', 'Drama', 'Thriller', 'Adventure', 'Animation', 'Family', 'Adventure', 'Animation', 'Comedy', 'Family', 'Adventure', 'Family', 'Fantasy', 'Animation', 'Adventure', 'Family', 'Adventure', 'Drama', 'War', 'Animation', 'Family', 'Adventure', 'Action', 'Thriller', 'Action', 'Fantasy', 'Comedy', 'Action', 'Thriller', 'Science Fiction', 'Adventure', 'Action', 'Adventure', 'Comedy', 'Science Fiction', 'Adventure', 'Action', 'Animation', 'Action', 'Adventure', 'Animation', 'Comedy', 'Family', 'Action', 'Thriller', 'Adventure', 'Fantasy', 'Animation', 'Family', 'Comedy', 'Drama', 'Action', 'War', 'History', 'Adventure', 'Drama', 'Action', 'Science Fiction', 'Action', 'Adventure', 'Fantasy', 'Action', 'Fantasy', 'Action', 'Adventure', 'Animation', 'Comedy', 'Family', 'Fantasy', 'Action', 'Action', 'Mystery', 'Science Fiction', 'Action', 'Adventure', 'Comedy', 'Crime', 'Thriller', 'Drama', 'Action', 'Science Fiction', 'Adventure', 'Action', 'Science Fiction', 'Thriller', 'Action', 'Adventure', 'Comedy', 'Drama', 'Mystery', 'Adventure', 'Action', 'Animation', 'Fantasy', 'Science Fiction', 'Thriller', 'Action', 'Adventure', 'Science Fiction', 'Adventure', 'Action', 'Thriller', 'Adventure', 'Adventure', 'Fantasy', 'Drama', 'Romance', 'Animation', 'Comedy', 'Family', 'Science Fiction', 'Action', 'Adventure', 'Adventure', 'Family', 'Fantasy', 'Western', 'Drama', 'Adventure', 'Thriller', 'Animation', 'Family', 'Animation', 'Comedy', 'Family', 'Western', 'Adventure', 'Family', 'Animation', 'Adventure', 'Comedy', 'Action', 'Drama', 'Mystery', 'Thriller', 'Adventure', 'Animation', 'Family', 'Comedy', 'Science Fiction', 'Action', 'Adventure', 'Adventure', 'Action', 'Science Fiction', 'Fantasy', 'Comedy', 'Animation', 'Science Fiction', 'Family', 'Adventure', 'Thriller', 'Science Fiction', 'Adventure', 'Action', 'Comedy', 'Thriller', 'Crime', 'Action', 'Adventure', 'Animation', 'Family', 'Fantasy', 'Action', 'Mystery', 'Thriller', 'Drama', 'Adventure', 'Adventure', 'Animation', 'Mystery', 'Adventure', 'Fantasy', 'Family', 'Drama', 'Science Fiction', 'Action', 'Adventure', 'Animation', 'Family', 'Adventure', 'Comedy', 'Fantasy', 'Family', 'Animation', 'Action', 'Comedy', 'Family', 'Science Fiction', 'Adventure', 'Fantasy', 'Family', 'Fantasy', 'Action', 'Comedy', 'Crime', 'Adventure', 'Fantasy', 'Action', 'Science Fiction', 'Adventure', 'Thriller', 'Thriller', 'Mystery', 'Animation', 'Adventure', 'Comedy', 'Family', 'Adventure', 'Action', 'Science Fiction', 'Thriller', 'Action', 'Thriller', 'Crime', 'Adventure', 'Action', 'Crime', 'Mystery', 'Adventure', 'Fantasy', 'Action', 'Action', 'Adventure', 'Science Fiction', 'Adventure', 'Fantasy', 'Action', 'Action', 'Thriller', 'Action', 'Crime', 'Fantasy', 'Family', 'Comedy', 'Fantasy', 'Action', 'Adventure', 'Science Fiction', 'Thriller', 'Adventure', 'Action', 'Thriller', 'Drama', 'Adventure', 'Fantasy', 'Action', 'Thriller', 'Adventure', 'Drama', 'Action', 'Thriller', 'Action', 'Fantasy', 'Horror', 'Action', 'Thriller', 'Action', 'Adventure', 'Comedy', 'Science Fiction', 'Adventure', 'Mystery', 'Family', 'Adventure', 'Animation', 'Comedy', 'Science Fiction', 'Action', 'Drama', 'Thriller', 'Action', 'Science Fiction', 'Action', 'Science Fiction', 'Action', 'Family', 'Science Fiction', 'Comedy', 'Drama', 'Romance', 'Action', 'Comedy', 'Action', 'Science Fiction', 'Adventure', 'Mystery', 'Science Fiction', 'Adventure', 'Action', 'Adventure', 'Action', 'Science Fiction', 'Animation', 'Comedy', 'Family', 'Action', 'Science Fiction', 'Adventure', 'Fantasy', 'Adventure', 'Action', 'Science Fiction', 'Adventure', 'Animation', 'Comedy', 'Family', 'Fantasy', 'Fantasy', 'Adventure', 'Comedy', 'Family', 'Drama', 'Action', 'History', 'War', 'Action', 'Adventure', 'Drama', 'Science Fiction', 'Action', 'Adventure', 'Fantasy', 'Comedy', 'Science Fiction', 'Thriller', 'Drama', 'Action', 'Adventure', 'Thriller', 'Fantasy', 'Action', 'Adventure', 'Comedy', 'Action', 'Adventure', 'Science Fiction', 'Action', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Action', 'Drama', 'Thriller', 'Adventure', 'Action', 'Thriller', 'Drama', 'History', 'War', 'Action', 'Thriller', 'Crime', 'Action', 'Comedy', 'Drama', 'Thriller', 'Adventure', 'Science Fiction', 'Thriller', 'Drama', 'Comedy', 'Action', 'Crime', 'Comedy', 'Action', 'War', 'Animation', 'Family', 'Adventure', 'Comedy', 'Fantasy', 'Animation', 'Family', 'Adventure', 'Science Fiction', 'Action', 'Science Fiction', 'Drama', 'Fantasy', 'Family', 'Comedy', 'Animation', 'Action', 'Adventure', 'Thriller', 'Science Fiction', 'Action', 'Adventure', 'Action', 'Thriller', 'Adventure', 'Fantasy', 'Action', 'Action', 'Adventure', 'Comedy', 'Drama', 'Comedy', 'Fantasy', 'Family', 'Action', 'Science Fiction', 'Drama', 'Action', 'Adventure', 'History', 'War', 'Animation', 'Fantasy', 'Family', 'Comedy', 'Romance', 'Family', 'Animation', 'Music', 'Drama', 'Adventure', 'Science Fiction', 'Action', 'Thriller', 'Science Fiction', 'Adventure', 'Comedy', 'Romance', 'Action', 'Crime', 'Thriller', 'Action', 'Drama', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'Mystery', 'Adventure', 'Fantasy', 'Family', 'Adventure', 'Action', 'Thriller', 'Thriller', 'Science Fiction', 'Action', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'History', 'Crime', 'Drama', 'Drama', 'Crime', 'Action', 'Thriller', 'Thriller', 'Drama', 'Crime', 'Comedy', 'Romance', 'Action', 'Comedy', 'Crime', 'Action', 'Drama', 'Mystery', 'Thriller', 'Drama', 'Western', 'Drama', 'Animation', 'Family', 'Adventure', 'Animation', 'Comedy', 'Family', 'Fantasy', 'Action', 'Adventure', 'Thriller', 'Adventure', 'Action', 'Thriller', 'Mystery', 'Fantasy', 'Action', 'Adventure', 'Family', 'Family', 'Fantasy', 'Animation', 'Adventure', 'Family', 'Fantasy', 'Action', 'Thriller', 'Romance', 'Action', 'Fantasy', 'Horror', 'Mystery', 'Drama', 'Thriller', 'Action', 'Crime', 'Drama', 'Comedy', 'Action', 'Crime', 'Fantasy', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'Drama', 'Science Fiction', 'Animation', 'Adventure', 'Family', 'Fantasy', 'Action', 'Crime', 'Action', 'Adventure', 'Adventure', 'Animation', 'Family', 'Fantasy', 'Science Fiction', 'Adventure', 'Comedy', 'Science Fiction', 'Action', 'Adventure', 'Thriller', 'Action', 'Crime', 'Thriller', 'Fantasy', 'Comedy', 'Family', 'Adventure', 'Thriller', 'Drama', 'Adventure', 'Action', 'History', 'Action', 'Comedy', 'Science Fiction', 'War', 'Action', 'Adventure', 'Drama', 'Thriller', 'Animation', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Adventure', 'Action', 'Fantasy', 'Drama', 'History', 'Crime', 'Drama', 'History', 'War', 'Animation', 'Comedy', 'Family', 'Action', 'Comedy', 'Science Fiction', 'Action', 'History', 'War', 'Comedy', 'Adventure', 'Fantasy', 'Action', 'Thriller', 'Science Fiction', 'Comedy', 'Drama', 'Romance', 'Adventure', 'Animation', 'Comedy', 'Family', 'Animation', 'Comedy', 'Adventure', 'Family', 'Romance', 'Fantasy', 'Family', 'Drama', 'Fantasy', 'Drama', 'Animation', 'Family', 'Adventure', 'Fantasy', 'Action', 'Adventure', 'Fantasy', 'Action', 'Adventure', 'Fantasy', 'Adventure', 'Fantasy', 'Action', 'Thriller', 'Thriller', 'Science Fiction', 'Drama', 'Mystery', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'Thriller', 'Action', 'Drama', 'Science Fiction', 'Adventure', 'Family', 'Fantasy', 'Action', 'Thriller', 'Western', 'History', 'War', 'Action', 'Adventure', 'Animation', 'Family', 'Action', 'Adventure', 'Adventure', 'Fantasy', 'Family', 'Action', 'Adventure', 'Comedy', 'Science Fiction', 'Animation', 'Comedy', 'Family', 'Action', 'Thriller', 'Action', 'Comedy', 'Crime', 'Thriller', 'Drama', 'Horror', 'Mystery', 'Thriller', 'Animation', 'Comedy', 'Family', 'Animation', 'Comedy', 'Family', 'Adventure', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Action', 'Adventure', 'Comedy', 'Crime', 'Thriller', 'Drama', 'Thriller', 'Crime', 'Animation', 'Family', 'Adventure', 'Action', 'Comedy', 'Thriller', 'Crime', 'Mystery', 'Drama', 'Action', 'Thriller', 'Action', 'Adventure', 'Crime', 'Mystery', 'Drama', 'Animation', 'Family', 'Adventure', 'Science Fiction', 'Adventure', 'Animation', 'Comedy', 'Family', 'Drama', 'Thriller', 'History', 'War', 'Comedy', 'Action', 'Action', 'Comedy', 'Science Fiction', 'Drama', 'Science Fiction', 'Adventure', 'Thriller', 'Fantasy', 'Comedy', 'Family', 'Mystery', 'Drama', 'Science Fiction', 'Mystery', 'Action', 'Science Fiction', 'Thriller', 'Crime', 'Thriller', 'Adventure', 'Family', 'Fantasy', 'Action', 'Adventure', 'Fantasy', 'Thriller', 'Action', 'Adventure', 'Comedy', 'Crime', 'Mystery', 'Thriller', 'Thriller', 'Action', 'Romance', 'Science Fiction', 'Adventure', 'Action', 'Crime', 'Thriller', 'Science Fiction', 'Animation', 'Adventure', 'Comedy', 'Family', 'Comedy', 'Science Fiction', 'Science Fiction', 'Action', 'Drama', 'Thriller', 'Crime', 'Thriller', 'Drama', 'Drama', 'History', 'Thriller', 'Adventure', 'Fantasy', 'Action', 'Romance', 'Drama', 'History', 'Fantasy', 'Action', 'Family', 'Drama', 'History', 'Action', 'Adventure', 'Drama', 'Adventure', 'Drama', 'Animation', 'Comedy', 'Action', 'Drama', 'Thriller', 'Action', 'Thriller', 'Thriller', 'Crime', 'Adventure', 'Action', 'Thriller', 'Animation', 'Comedy', 'Family', 'Fantasy', 'Comedy', 'Family', 'Fantasy', 'Romance', 'Action', 'Thriller', 'Comedy', 'Family', 'Action', 'Comedy', 'Comedy', 'Romance', 'Action', 'Drama', 'Thriller', 'Comedy', 'Romance', 'Crime', 'Thriller', 'Adventure', 'Animation', 'Family', 'Adventure', 'Action', 'Science Fiction', 'War', 'Adventure', 'Action', 'Comedy', 'Thriller', 'Adventure', 'Fantasy', 'Action', 'Comedy', 'Family', 'Drama', 'History', 'Romance', 'Action', 'Crime', 'Drama', 'Thriller', 'Drama', 'Animation', 'Family', 'Comedy', 'Fantasy', 'Drama', 'Mystery', 'Action', 'Thriller', 'Drama', 'Drama', 'Music', 'Adventure', 'Fantasy', 'Drama', 'Comedy', 'Science Fiction', 'Family', 'Action', 'Adventure', 'Comedy', 'Action', 'Thriller', 'Adventure', 'Science Fiction', 'Fantasy', 'Comedy', 'Romance', 'Science Fiction', 'Mystery', 'Adventure', 'Comedy', 'Action', 'Science Fiction', 'Comedy', 'Drama', 'Fantasy', 'Romance', 'Horror', 'Comedy', 'Fantasy', 'Comedy', 'Family', 'Adventure', 'Fantasy', 'Science Fiction', 'Adventure', 'Fantasy', 'Science Fiction', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Science Fiction', 'Fantasy', 'Comedy', 'Thriller', 'Adventure', 'Action', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'Adventure', 'Fantasy', 'Comedy', 'Action', 'Fantasy', 'Comedy', 'Animation', 'Family', 'Animation', 'Family', 'Comedy', 'Family', 'Fantasy', 'Action', 'Drama', 'Romance', 'Action', 'Comedy', 'Crime', 'Thriller', 'Comedy', 'Drama', 'Comedy', 'Fantasy', 'Family', 'Music', 'Animation', 'Comedy', 'Action', 'Comedy', 'Thriller', 'Drama', 'Comedy', 'Romance', 'Drama', 'Thriller', 'Mystery', 'Comedy', 'Romance', 'Drama', 'Animation', 'Comedy', 'Family', 'Science Fiction', 'Action', 'Crime', 'Science Fiction', 'Thriller', 'Fantasy', 'Comedy', 'Family', 'Romance', 'Thriller', 'Crime', 'Drama', 'Romance', 'Comedy', 'Action', 'Thriller', 'Crime', 'Mystery', 'Thriller', 'Action', 'Drama', 'Action', 'Thriller', 'Science Fiction', 'Comedy', 'Family', 'Science Fiction', 'Horror', 'Thriller', 'Fantasy', 'Mystery', 'Animation', 'Comedy', 'Drama', 'Family', 'Fantasy', 'Action', 'Comedy', 'Crime', 'Mystery', 'Family', 'Drama', 'Science Fiction', 'Thriller', 'Action', 'Drama', 'Mystery', 'Thriller', 'War', 'Drama', 'Action', 'Action', 'Adventure', 'Comedy', 'Romance', 'Comedy', 'Family', 'Animation', 'Adventure', 'Western', 'Animation', 'Adventure', 'Comedy', 'Family', 'Comedy', 'Romance', 'Family', 'Adventure', 'Family', 'Science Fiction', 'Drama', 'Thriller', 'Mystery', 'Romance', 'Drama', 'Animation', 'Comedy', 'Family', 'Animation', 'Family', 'Music', 'Science Fiction', 'Adventure', 'Action', 'Action', 'Adventure', 'Family', 'Fantasy', 'Action', 'Crime', 'Thriller', 'Action', 'Adventure', 'Drama', 'Fantasy', 'Romance', 'Comedy', 'Fantasy', 'Romance', 'Adventure', 'Fantasy', 'Action', 'Comedy', 'Thriller', 'Comedy', 'Fantasy', 'Science Fiction', 'Mystery', 'Drama', 'Horror', 'Action', 'Adventure', 'Drama', 'Action', 'Science Fiction', 'Thriller', 'Drama', 'Thriller', 'Action', 'Adventure', 'Thriller', 'Animation', 'Family', 'Adventure', 'Action', 'Science Fiction', 'War', 'Animation', 'Comedy', 'Family', 'Drama', 'Music', 'Romance', 'Action', 'Adventure', 'Science Fiction', 'Drama', 'Adventure', 'Adventure', 'Comedy', 'Drama', 'Family', 'Fantasy', 'Fantasy', 'Action', 'Adventure', 'Thriller', 'Action', 'Science Fiction', 'Adventure', 'Fantasy', 'Animation', 'Family', 'Documentary', 'Family', 'Thriller', 'Science Fiction', 'Adventure', 'Action', 'Action', 'Adventure', 'History', 'Romance', 'Drama', 'Comedy', 'Animation', 'Drama', 'Romance', 'Family', 'Animation', 'Drama', 'Adventure', 'Action', 'Science Fiction', 'Animation', 'Family', 'Comedy', 'Crime', 'Thriller', 'Horror', 'Western', 'Adventure', 'Comedy', 'Action', 'Crime', 'Thriller', 'Adventure', 'Animation', 'Fantasy', 'Science Fiction', 'Thriller', 'Action', 'Adventure', 'Animation', 'Comedy', 'Family', 'Animation', 'Family', 'Fantasy', 'Action', 'Thriller', 'Science Fiction', 'Animation', 'Comedy', 'Family', 'Action', 'Adventure', 'Science Fiction', 'Adventure', 'Action', 'Science Fiction', 'Family', 'Animation', 'Drama', 'Action', 'Thriller', 'Science Fiction', 'Adventure', 'Action', 'Science Fiction', 'Action', 'Thriller', 'Crime', 'Action', 'Adventure', 'Thriller', 'Animation', 'Family', 'Comedy', 'Adventure', 'Comedy', 'Romance', 'Family', 'Comedy', 'Music', 'Romance', 'Horror', 'Mystery', 'Thriller', 'Action', 'Adventure', 'Comedy', 'Family', 'Thriller', 'Crime', 'Comedy', 'Comedy', 'Drama', 'Comedy', 'Family', 'Action', 'Adventure', 'Thriller', 'Comedy', 'Drama', 'History', 'Animation', 'Action', 'Comedy', 'Family', 'Drama', 'Comedy', 'Crime', 'Drama', 'Action', 'History', 'Thriller', 'Action', 'Drama', 'War', 'Action', 'Comedy', 'Thriller', 'Romance', 'Comedy', 'Action', 'Adventure', 'Comedy', 'Animation', 'Comedy', 'Family', 'Fantasy', 'Action', 'Comedy', 'Crime', 'Romance', 'Action', 'Adventure', 'Drama', 'Romance', 'Drama', 'History', 'Romance', 'Fantasy', 'Action', 'Drama', 'Mystery', 'Drama', 'Thriller', 'Crime', 'Animation', 'Action', 'Science Fiction', 'Family', 'Adventure', 'Action', 'Adventure', 'Comedy', 'Thriller', 'A

In [480]:
import ast

def convert(obj):
  l=[]
  for i in ast.literal_eval(obj):
    l.append(i['name'])
  return l

movies["genres"].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [481]:
movies["genres"]= movies["genres"].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [482]:
movies["keywords"].apply(convert)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [483]:
movies["keywords"]=movies["keywords"].apply(convert)

In [484]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [485]:
def convert_3(obj):
  l=[]
  counter=0
  for i in ast.literal_eval(obj):
    if counter !=3:
      l.append(i["name"])
      counter+=1
    else:
      break
  return l

In [486]:
movies["cast"].apply(convert_3)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [487]:
movies["cast"]=movies["cast"].apply(convert_3)

In [488]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [489]:
def convert_4(obj):
  l=[]
  for i in ast.literal_eval(obj):
      if i["job"] == "Director":
        l.append(i["name"])
        break
  return l

movies["crew"].apply(convert_4)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [490]:
movies["overview"]=movies["overview"].apply(lambda x: x.split())

In [491]:
movies["crew"]= movies["crew"].apply(convert_4)

In [492]:
for val in movies["cast"][0]:
  val= val.replace(" ","")
  print(val)

SamWorthington
ZoeSaldana
SigourneyWeaver

In [493]:
movies["cast"]=movies["cast"].apply(lambda x: [i.replace(" ","") for i in x])

In [494]:
movies["crew"]=movies["crew"].apply(lambda x: [i.replace(" ","") for i in x])

In [495]:
movies["genres"]=movies["genres"].apply(lambda x: [i.replace(" ","") for i in x])

In [496]:
movies["keywords"]=movies["keywords"].apply(lambda x: [i.replace(" ","") for i in x])

In [497]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [498]:
movies["tags"]= movies["overview"]+movies["genres"]+movies["keywords"]+movies["cast"]+movies["crew"]

In [499]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [500]:
movies.drop(columns=["overview","genres","keywords","cast","crew"],inplace=True,axis=1)

In [501]:
movies.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [502]:
movies["tags"]=movies["tags"].apply(lambda x: " ".join([i for i in x]))

In [503]:
movies.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [504]:
movies["tags"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [505]:
movies["tags"]=movies["tags"].apply(lambda x: x.lower())

In [506]:
movies["tags"][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [507]:
import nltk
nltk.download('wordnet')
from nltk.stem import PorterStemmer,WordNetLemmatizer
movies["tags"]=movies["tags"].apply(lambda x: WordNetLemmatizer().lemmatize(x))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [508]:
## Stemming
def stem(text):
  y=[]
  for i in text.split():
    y.append(PorterStemmer().stem(i))
  return " ".join(y)

In [509]:
movies["tags"]= movies["tags"].apply(stem)

In [510]:
stem("adams")

'adam'

In [511]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000,stop_words="english")

In [512]:
vectors=cv.fit_transform(movies["tags"]).toarray()

In [513]:
vectors.shape

(4806, 5000)

In [514]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [515]:
cv.get_feature_names_out()[:200]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '17th', '18', '18th', '18thcenturi', '19', '1910', '1920',
       '1930', '1940', '1944', '1950', '1950s', '1960', '1960s', '1970',
       '1970s', '1971', '1974', '1976', '1980', '1985', '1990', '1999',
       '19th', '19thcenturi', '20', '200', '2003', '2009', '20th', '21st',
       '23', '24', '25', '30', '300', '3d', '40', '50', '500', '60', '70',
       '80', 'aaron', 'aaroneckhart', 'abandon', 'abduct',
       'abigailbreslin', 'abil', 'abl', 'aboard', 'abov', 'abus',
       'academ', 'academi', 'accept', 'access', 'accid', 'accident',
       'acclaim', 'accompani', 'accomplish', 'account', 'accus', 'ace',
       'achiev', 'acquaint', 'act', 'action', 'actionhero', 'activ',
       'activist', 'activities', 'actor', 'actress', 'actual', 'ad',
       'adam', 'adamsandl', 'adamshankman', 'adapt', 'add', 'addict',
       'adjust', 'admir', 'admit', 'adolesc', 'adopt', 'ador',
       'adrienbrodi', 'adult', 'adultanim', 'adulteri', 'adulthood',
       'advanc', 'adventur', 'adventure', 'adventures', 'advertis',
       'advic', 'advis', 'affair', 'affect', 'afghanistan', 'africa',
       'african', 'africanamerican', 'aftercreditssting', 'afterlif',
       'aftermath', 'ag', 'age', 'agediffer', 'agenc', 'agency', 'agenda',
       'agent', 'agents', 'aggress', 'ago', 'agre', 'ahead', 'aid',
       'aidanquinn', 'ail', 'aim', 'air', 'airplan', 'airplanecrash',
       'airport', 'aka', 'al', 'alabama', 'alan', 'alaska', 'albert',
       'alcatraz', 'alcohol', 'alecbaldwin', 'alex', 'alexkendrick',
       'alfredhitchcock', 'alfredmolina', 'ali', 'alic', 'alice', 'alien',
       'alieninvas', 'alienlife', 'alienplanet', 'aliens', 'alik', 'aliv',
       'alive', 'allen', 'alli', 'allianc', 'allow', 'alon', 'alongsid',
       'alpacino', 'alpha', 'alreadi', 'alter', 'altern', 'alway',
       'alyssa', 'alzheimer', 'amanda', 'amandapeet', 'amandaseyfri',
       'amateur', 'amaz', 'amazon', 'ambassador', 'ambit', 'ambiti',
       'ambul', 'ambush', 'america', 'american', 'americanabroad',
       'americancivilwar', 'americanfootbal', 'americanfootballplay',
       'amid', 'amidst', 'amnesia', 'amp'], dtype=object)

In [517]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [518]:
similarity.shape

(4806, 4806)

In [519]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [524]:
## I need first higher values of count 5
sorted(similarity[0], reverse=True)

[1.0000000000000002,
 0.28676966733820225,
 0.26901379342448517,
 0.2605130246476754,
 0.255608593705383,
 0.25038669783359574,
 0.24511108480187255,
 0.24455799402225922,
 0.2367785320221084,
 0.23179316248638276,
 0.23174488732966075,
 0.2278389747471728,
 0.2252817784447915,
 0.21853668936906193,
 0.21239769762143662,
 0.2108663315950723,
 0.2105263157894737,
 0.20443988269091456,
 0.20437977982832192,
 0.20395079136182276,
 0.2029530274475215,
 0.2029530274475215,
 0.20277677641345318,
 0.2024645717996314,
 0.2020475485519274,
 0.1979082783981174,
 0.19767387315371682,
 0.1976738731537168,
 0.19672236884115843,
 0.19252140716412977,
 0.19134594929397597,
 0.19088542889273336,
 0.19088542889273336,
 0.19007487139298027,
 0.1892994097121204,
 0.18731716231633883,
 0.1873171623163388,
 0.18693292157876878,
 0.1860807318911967,
 0.18394180184548975,
 0.18394180184548975,
 0.1813690625275029,
 0.18074256993863339,
 0.17996850826633903,
 0.17954621161490197,
 0.1777046633277277,
 0.177343107178349,
 0.17699808135119718,
 0.17521916101261562,
 0.17521916101261562,
 0.17521916101261562,
 0.1748149640244195,
 0.17316974359835272,
 0.17292861596651865,
 0.1711905958155815,
 0.1711905958155815,
 0.17040572913692198,
 0.16943474841747155,
 0.1675415633166782,
 0.16742770563222897,
 0.16742770563222897,
 0.16692446522239718,
 0.16563698349810535,
 0.16452254913212452,
 0.16426202236672155,
 0.16222142113076254,
 0.16122923187750418,
 0.16059101370939324,
 0.15907119074394446,
 0.15907119074394446,
 0.15789473684210528,
 0.15737789507292674,
 0.15609763526361567,
 0.15511334686589626,
 0.1540171257313038,
 0.15389675281277312,
 0.15389675281277312,
 0.152008377581442,
 0.15018785229652767,
 0.15018785229652767,
 0.15018785229652765,
 0.14843120879858804,
 0.14843120879858804,
 0.14808721943977307,
 0.14673479641335554,
 0.14659886790209342,
 0.14601068654819693,
 0.14567913668701626,
 0.14567913668701626,
 0.14509525002200235,
 0.14509525002200235,
 0.14509525002200233,
 0.14421498760030763,
 0.1442149876003076,
 0.14350946197048198,
 0.14350946197048198,
 0.1433848336691011,
 0.1433848336691011,
 0.1433848336691011,
 0.1419745572840903,
 0.1419745572840903,
 0.14159846508095775,
 0.14159846508095775,
 0.1411956236812263,
 0.1411956236812263,
 0.1411956236812263,
 0.1411956236812263,
 0.14048787173725413,
 0.13977653617040256,
 0.1391037210186643,
 0.1391037210186643,
 0.13872950617564817,
 0.13834289277321493,
 0.13834289277321493,
 0.13834289277321493,
 0.13834289277321493,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13710212427677043,
 0.13629325512727639,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13530201829834768,
 0.13518451760896877,
 0.13497638119975428,
 0.13476498501489081,
 0.13369695534647594,
 0.13369695534647594,
 0.13369695534647594,
 0.13334518676566626,
 0.13334518676566626,
 0.1324532357065044,
 0.1324532357065044,
 0.1324532357065044,
 0.13157894736842107,
 0.13124359177794215,
 0.12988108336653278,
 0.12988108336653278,
 0.12988108336653278,
 0.12977713690461004,
 0.12977713690461004,
 0.12977713690461004,
 0.12892051277806202,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12824729401064427,
 0.12725695259515557,
 0.12725695259515557,
 0.12725695259515557,
 0.126673647984535,
 0.12565617248750865,
 0.12565617248750865,
 0.12515654358043973,
 0.12515654358043973,
 0.12515654358043973,
 0.12515654358043973,
 0.12487810821089254,
 0.12487810821089254,
 0.12487810821089254,
 0.12487810821089254,
 0.12462194771917919,
 0.12361284651454937,
 0.12262786789699316,
 0.12262786789699316,
 0.12262786789699313,
 0.12227899701112963,
 0.12227899701112963,
 0.12227899701112963,
 0.12166606584807191,
 0.12166606584807191,
 0.12166606584807191,
 0.12072654548783007,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.1204950466257556,
 0.11980845957463077,
 0.11959121830873498,
 0.11959121830873498,
 0.11959121830873498,
 0.11959121830873498,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11846977555181847,
 0.11803342130469506,
 0.11803342130469505,
 0.11803342130469505,
 0.11803342130469505,
 0.11803342130469505,
 0.11712303424679457,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.11707322644771176,
 0.116543309349613,
 0.116543309349613,
 0.116543309349613,
 0.116543309349613,
 0.1163350101494222,
 0.11587244366483038,
 0.11551284429847784,
 0.11506355109724453,
 0.1147078669352809,
 0.1147078669352809,
 0.11470786693528087,
 0.11470786693528087,
 0.1141270638770543,
 0.11357771260606365,
 0.11357771260606365,
 0.11295649894498103,
 0.11295649894498103,
 0.1124803176664619,
 0.1124803176664619,
 0.1124803176664619,
 0.11243619908556624,
 0.11239029738980327,
 0.11164843913471803,
 0.11164843913471803,
 0.11164843913471803,
 0.11164843913471803,
 0.11141412945539662,
 0.11141412945539662,
 0.11141412945539661,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11092107999698035,
 0.11092107999698035,
 0.11037769642208699,
 0.11020775375559676,
 0.11020775375559674,
 0.10968169942141637,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10968169942141635,
 0.10936965981495178,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10876595882948199,
 0.10838874619051501,
 0.10838874619051501,
 0.10838874619051501,
 0.108388746190515,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.1074861545850028,
 0.10743376064838502,
 0.1068366854693644,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.10650358071057624,
 0.10650358071057624,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10619884881071831,
 0.10559715077387793,
 0.10559715077387793,
 0.10559715077387793,
 0.10526315789473685,
 0.10526315789473685,
 0.10526315789473685,
 0.10526315789473685,
 0.10471347707292386,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10385162309931599,
 0.10385162309931599,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.10301070542879115,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10218988991416095,
 0.10147651372376076,
 0.10147651372376076,
 0.10147651372376076,
 0.10138838820672659,
 0.101338918387628,
 0.101338918387628,
 0.10133891838762799,
 0.10060545457319173,
 0.10060545457319173,
 0.10060545457319173,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09933992677987831,
 0.09909250441117726,
 0.09909250441117726,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.0989541391990587,
 0.09836118442057921,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.09733285267845754,
 0.0967301666813349,
 0.0967301666813349,
 0.09567297464698798,
 0.09567297464698798,
 0.09567297464698798,
 0.09567297464698798,
 0.09558988911273408,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09544271444636668,
 0.09493290614465533,
 0.09464970485606021,
 0.09464970485606021,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816941,
 0.09365858115816939,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09269795493186431,
 0.09243423333081695,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09183979479633063,
 0.09183979479633063,
 0.09125667909262308,
 0.09125667909262308,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.09037128496931669,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08998425413316952,
 0.08977310580745099,
 0.0891313035643173,
 0.08903057122447033,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08830215713766959,
 0.08797691788472335,
 0.08749572785196143,
 0.08749572785196143,
 0.08746392856766495,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08740748201220976,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08671099695241201,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08603090020146065,
 0.08594700851870801,
 0.08594700851870801,
 0.08594700851870801,
 0.08520286456846099,
 0.08520286456846099,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08471737420873576,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.08447772061910234,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08321783316232578,
 0.0830812984794528,
 0.0830812984794528,
 0.0830812984794528,
 0.08240856434303293,
 0.08240856434303293,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606226,
 0.08175191193132876,
 0.08175191193132876,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08048436365855338,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.07992075789278003,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.0792740035289418,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07894736842105264,
 0.07878168645790681,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07868894753646337,
 0.07843304784240032,
 0.0781166566864507,
 0.0781166566864507,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07755667343294813,
 0.07755667343294813,
 0.0770085628656519,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.07647191129018727,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.076004188790721,
 0.07594632491572426,
 0.07543142864047142,
 0.07530940414109724,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07492686492653551,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07421560439929402,
 0.07394738666465357,
 0.07394738666465357,
 0.07394738666465357,
 0.0734718358370645,
 0.0734718358370645,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667777,
 0.07336739820667777,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07209840939145001,
 0.07209840939145001,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524099,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07098727864204515,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07079923254047887,
 0.07038153430777869,
 0.07038153430777869,
 0.07024393586862707,
 0.07024393586862707,
 0.07024393586862707,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06952346619889824,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06765100914917384,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.06748819059987714,
 0.0672863110252489,
 0.06684847767323797,
 0.06684847767323797,
 0.06684847767323797,
 0.06684847767323797,
 0.06657426652986062,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.0662266178532522,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06578947368421054,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06562179588897107,
 0.06554735253444621,
 0.06521546507260247,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.065033247714309,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06488856845230502,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06446025638903101,
 0.06424925662032356,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06390214842634574,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,
 0.06362847629757779,

In [534]:
sorted(list(enumerate(similarity[0])), reverse=True,key=lambda x:x[1])[0:6]

[(0, 1.0000000000000002),
 (1214, 0.28676966733820225),
 (2405, 0.26901379342448517),
 (3728, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574)]

In [522]:
movies[movies["title"]=="Avatar"].index[0]

0

In [523]:
movies[movies["title"]=="Batman"].index[0]

1360

In [557]:
movies.iloc[1204].title

'Secret Window'

In [589]:

def recommend(movie):
  movie_index= movies[movies["title"]==movie].index[0]
  distances=similarity[movie_index]
  movies_list= sorted(list(enumerate(distances)), reverse=True,key=lambda x:x[1])[1:6]
  for i in movies_list:
    print(movies.iloc[i[0]].title)

In [590]:
recommend("Avatar")

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [585]:
recommend("Batman")

Batman
Batman & Robin
Batman Begins
Batman Returns
The R.M.

In [563]:
recommend("Adam")

Easy Money
Nine Queens
The Infiltrator
Trash
Killer Joe

In [ ]:
import pickle
pickle.dump(movies,open("movies.pkl","wb"))
pickle.dump(movies['title'].to_dict(), open("movies_list.pkl","wb"))
pickle.dump(similarity,open("similarity.pkl","wb"))