In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
## Import Required SKlearn Libraries

from sklearn.model_selection import train_test_split, RandomizedSearchCV, GridSearchCV, StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor

In [5]:
df= pd.read_csv("/content/cardekho_imputated.csv",index_col=0)
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [6]:
df.columns

Index(['car_name', 'brand', 'model', 'vehicle_age', 'km_driven', 'seller_type',
       'fuel_type', 'transmission_type', 'mileage', 'engine', 'max_power',
       'seats', 'selling_price'],
      dtype='object')

In [ ]:
df.car_name.value_counts()

In [ ]:
df.brand.value_counts()

In [ ]:
df.model.value_counts()

In [11]:
df.seller_type.value_counts()

seller_type
Dealer              9539
Individual          5699
Trustmark Dealer     173
Name: count, dtype: int64

In [12]:
df.fuel_type.value_counts()

fuel_type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64

In [13]:
df.transmission_type.value_counts()

transmission_type
Manual       12225
Automatic     3186
Name: count, dtype: int64

In [14]:
## Check for null values
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [15]:
df.model.unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [16]:
len(df.model.unique())

120

In [17]:
df.drop("car_name",axis=1, inplace=True)
df.head()

,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [18]:
df.drop("brand",axis=1,inplace=True)
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15411 non-null  object
 1   vehicle_age        15411 non-null  int64
 2   km_driven          15411 non-null  int64
 3   seller_type        15411 non-null  object
 4   fuel_type          15411 non-null  object
 5   transmission_type  15411 non-null  object
 6   mileage            15411 non-null  float64
 7   engine             15411 non-null  int64
 8   max_power          15411 non-null  float64
 9   seats              15411 non-null  int64
 10  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 1.4+ MB

In [34]:
## Getting All Different Types OF Features
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical Features :', len(num_features))
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of Categorical Features :', len(cat_features))
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print('Num of Discrete Features :',len(discrete_features))
continuous_features=[feature for feature in num_features if feature not in discrete_features]
print('Num of Continuous Features :',len(continuous_features))

Num of Numerical Features : 7
Num of Categorical Features : 4
Num of Discrete Features : 2
Num of Continuous Features : 5

In [20]:
num_feat= df.select_dtypes(exclude="object").columns
cat_feat=df.select_dtypes(include="object").columns
print(num_feat,"\n",len(num_feat))
print(cat_feat,"\n",len(cat_feat))

Index(['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats',
       'selling_price'],
      dtype='object')
 7
Index(['model', 'seller_type', 'fuel_type', 'transmission_type'], dtype='object')
 4

In [80]:
X= df.iloc[:,:-1]
y=df.iloc[:,-1]
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [81]:
le1=LabelEncoder()
X['model']=le1.fit_transform(X['model'])

In [68]:
y.head()
y.shape

(15411,)

In [69]:
X.shape

(15411, 10)

In [ ]:
cat_feat=cat_feat.drop('model')
cat_feat

## Standarizing of models X_train, X_test

In [ ]:
num_feat=num_feat.drop("selling_price")
num_feat

In [82]:
print(cat_feat)
print(num_feat)
# model_feat=np.array(['model'],dtype="object")
# print(model_feat)
model_feat=['model']

Index(['seller_type', 'fuel_type', 'transmission_type'], dtype='object')
Index(['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats'], dtype='object')

In [83]:
from sklearn.compose import ColumnTransformer

cv= ColumnTransformer(transformers=[
    ("StandarScaler",StandardScaler(),num_feat),
    ("onehot",OneHotEncoder(drop='first'),cat_feat)
], remainder='passthrough')

In [73]:
cv

ColumnTransformer(remainder='passthrough',
                  transformers=[('StandarScaler', StandardScaler(),
                                 Index(['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats'], dtype='object')),
                                ('onehot', OneHotEncoder(drop='first'),
                                 Index(['seller_type', 'fuel_type', 'transmission_type'], dtype='object'))])

In [84]:
X_train.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [85]:
X=cv.fit_transform(X)

In [86]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.20, random_state=7)
print(X_train.shape)
print(y_train.shape)

(12328, 14)
(12328,)

In [87]:
X_train[:10]

array([[ 6.51688048e-01, -2.63411549e-01,  1.57954557e-01,
        -5.54717742e-01, -5.04711519e-01, -4.03022414e-01,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.17000000e+02],
       [-1.00768088e+00, -3.66149270e-01, -1.92070558e-01,
        -5.54717742e-01, -4.35828791e-01, -4.03022414e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  5.40000000e+01],
       [ 9.83561835e-01,  5.69261896e-01, -1.65450426e+00,
         1.93429668e+00,  3.28530158e-02,  3.31167760e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  6.00000000e+01],
       [-1.00768088e+00, -7.81071727e-01,  7.93274114e-01,
        -9.34690646e-01, -7.81638703e-01, -4.03022414e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  6.40000000e+01],
       [-1.20595237e-02, -3.02546038e-01, -1.92070558e-01,
        -5.54717742e-01, -4.32570824e-01, -4.03022414e-01,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  5.40000000e+01],
       [-6.75807096e-01, -8.50680747e-01,  3.61736301e-01,
        -5.54717742e-01, -4.37225062e-01, -4.03022414e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  8.80000000e+01],
       [-6.75807096e-01, -3.99413586e-01,  1.93916041e-01,
        -9.36609701e-01, -7.80707856e-01, -4.03022414e-01,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+02],
       [-1.00768088e+00, -5.73775173e-01, -1.48916777e-01,
         1.84118459e-01,  5.96015862e-01, -4.03022414e-01,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  9.70000000e+01],
       [ 1.97918319e+00, -1.08810942e-01, -6.47582693e-01,
        -5.54717742e-01, -4.79113208e-01, -4.03022414e-01,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.18000000e+02],
       [-6.75807096e-01, -3.99413586e-01,  1.04020964e+00,
        -9.34690646e-01, -7.81638703e-01, -4.03022414e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  6.40000000e+01]])

In [88]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022,1.0,0.0,0.0,0.0,0.0,1.0,1.0,7.0
1,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022,1.0,0.0,0.0,0.0,0.0,1.0,1.0,54.0
2,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022,1.0,0.0,0.0,0.0,0.0,1.0,1.0,118.0
3,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022,1.0,0.0,0.0,0.0,0.0,1.0,1.0,7.0
4,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022,0.0,0.0,1.0,0.0,0.0,0.0,1.0,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022,0.0,0.0,0.0,0.0,0.0,1.0,1.0,117.0
15407,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444,0.0,0.0,0.0,0.0,0.0,1.0,1.0,42.0
15408,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022,0.0,0.0,1.0,0.0,0.0,0.0,1.0,77.0
15409,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444,0.0,0.0,1.0,0.0,0.0,0.0,1.0,114.0
15410,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022,0.0,0.0,0.0,0.0,0.0,1.0,0.0,25.0

In [89]:
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [90]:
##Create a Function to Evaluate Model
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [91]:
## Beginning Model Training
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),

}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)


    print(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')

    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 540361.4668
- Mean Absolute Error: 263720.3626
- R2 Score: 0.6233
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 558469.7876
- Mean Absolute Error: 266852.1288
- R2 Score: 0.6521
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 540361.4713
- Mean Absolute Error: 263718.3074
- R2 Score: 0.6233
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 558470.4505
- Mean Absolute Error: 266849.2791
- R2 Score: 0.6521
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 540361.8689
- Mean Absolute Error: 263682.1060
- R2 Score: 0.6233
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 558483.8847
- Mean Absolute Error: 266810.5020
- R2 Score: 0.6520
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 315273.6062
- Mean Absolute Error: 85605.1164
- R2 Score: 0.8718
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 340919.3523
- Mean Absolute Error: 110042.4181
- R2 Score: 0.8703
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 20787.1663
- Mean Absolute Error: 5189.3846
- R2 Score: 0.9994
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 351789.5985
- Mean Absolute Error: 124827.6841
- R2 Score: 0.8619
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 127289.5860
- Mean Absolute Error: 39832.8018
- R2 Score: 0.9791
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 320758.5462
- Mean Absolute Error: 104542.0126
- R2 Score: 0.8852
===================================

In [92]:

#Initialize few parameter for Hyperparamter tuning
knn_params = {"n_neighbors": [2, 3, 10, 20, 40, 50]}
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

In [93]:

# Models list for Hyperparameter tuning
randomcv_models = [('KNN', KNeighborsRegressor(), knn_params),
                   ("RF", RandomForestRegressor(), rf_params)

                   ]

In [94]:
##Hyperparameter Tuning
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                   param_distributions=params,
                                   n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
    random.fit(X_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:320: UserWarning: The total space of parameters 6 is smaller than n_iter=100. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 3 folds for each of 100 candidates, totalling 300 fits

/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning:
72 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
72 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.10/dist-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:1103: UserWarning: One or more of the test scores are non-finite: [       nan 0.83169522 0.82284771 0.82702674        nan 0.84166
 0.82650847 0.82430905 0.84226705        nan 0.76265178 0.83137733
        nan        nan 0.85159921 0.77857729 0.84541379 0.82676113
 0.81971727 0.84020439 0.84953158        nan        nan 0.82700113
 0.78412824 0.84426926 0.83638952 0.83110363        nan 0.78022065
        nan 0.8365471         nan 0.82544121 0.85160196 0.82975481
 0.78516801 0.81553434 0.83055467 0.83852085 0.85036631 0.78721802
 0.83551039 0.84403938 0.76099232 0.84296609        nan        nan
        nan 0.82359911 0.8496471  0.83427369 0.78255882 0.8340486
 0.84852792        nan 0.82639689 0.81867208 0.77100702 0.79245941
 0.76681788 0.8227972  0.83028127 0.84012494 0.78280551        nan
 0.77007966 0.84558736 0.82169108 0.84074079        nan        nan
 0.83376667 0.8321113         nan 0.82098762 0.82923561 0.83709558
 0.82942594        nan 0.84799874 0.75807167 0.83153381 0.82494824
 0.8257982  0.82350206        nan 0.834981          nan 0.76742917
 0.84896312        nan 0.83065654 0.8339467  0.85030939 0.84107614
        nan 0.83180217        nan 0.85097505]
  warnings.warn(

---------------- Best Params for KNN -------------------
{'n_neighbors': 2}
---------------- Best Params for RF -------------------
{'n_estimators': 1000, 'min_samples_split': 2, 'max_features': 5, 'max_depth': None}

In [96]:
## Retraining the models with best parameters
models = {
    "Random Forest Regressor": RandomForestRegressor(n_estimators=100, min_samples_split=2, max_features=5, max_depth=None,
                                                     n_jobs=-1),
     "K-Neighbors Regressor": KNeighborsRegressor(n_neighbors=2, n_jobs=-1)

}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')

    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print('='*35)
    print('\n')

Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 133303.5988
- Mean Absolute Error: 39034.6664
- R2 Score: 0.9771
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 320234.3962
- Mean Absolute Error: 104175.2522
- R2 Score: 0.8856
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 208272.5707
- Mean Absolute Error: 60491.8884
- R2 Score: 0.9440
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 253437.3106
- Mean Absolute Error: 106336.9891
- R2 Score: 0.9283
===================================