In [31]:
import numpy as np
import pandas as pd
import pickle

In [32]:
df=pd.read_csv("C:\\Users\\ssan\\Downloads\\Cursor_Projects\\Deep_Learning\\Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [33]:
df.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [34]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [35]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder

labelencode= LabelEncoder()
df['Gender']= labelencode.fit_transform(df['Gender'])
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [36]:
df.tail()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [37]:
df['Gender'].value_counts()

Gender
1    5457
0    4543
Name: count, dtype: int64

In [38]:
onehotencoder=OneHotEncoder(handle_unknown='ignore')
onehotencode_geo= onehotencoder.fit_transform(df[['Geography']])
onehotencode_geo.toarray()

geo_df= pd.DataFrame(onehotencode_geo.toarray(), columns=onehotencoder.get_feature_names_out(['Geography']))
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [39]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [40]:
df=pd.concat([df.drop('Geography',axis=1),geo_df],axis=1).reset_index(drop=True)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [41]:
from sklearn.model_selection import train_test_split

X=df.drop('EstimatedSalary',axis=1)
y=df['EstimatedSalary']

X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.20,random_state=77)
X_train.shape, y_train.shape

((8000, 12), (8000,))

In [42]:
## Normalization process

from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
print(X_train, X_test)

[[ 1.38301861  0.91025899 -0.37170256 ... -1.00727647 -0.57677292
   1.74719344]
 [ 0.34719703 -1.09858844 -1.23104766 ...  0.99277609 -0.57677292
  -0.57234647]
 [-1.14438603  0.91025899 -0.18073698 ...  0.99277609 -0.57677292
  -0.57234647]
 ...
 [ 0.3886299   0.91025899 -0.94459929 ...  0.99277609 -0.57677292
  -0.57234647]
 [ 0.53364492  0.91025899  0.58312533 ...  0.99277609 -0.57677292
  -0.57234647]
 [-2.03519259  0.91025899 -0.46718535 ...  0.99277609 -0.57677292
  -0.57234647]] [[ 0.65794351  0.91025899 -0.46718535 ... -1.00727647 -0.57677292
   1.74719344]
 [ 0.78224209 -1.09858844  0.86957369 ... -1.00727647 -0.57677292
   1.74719344]
 [ 1.08263035  0.91025899 -0.94459929 ...  0.99277609 -0.57677292
  -0.57234647]
 ...
 [ 1.4451679   0.91025899 -1.23104766 ...  0.99277609 -0.57677292
  -0.57234647]
 [-1.20653533  0.91025899  1.15602206 ... -1.00727647 -0.57677292
   1.74719344]
 [-1.03044566  0.91025899  0.39215975 ...  0.99277609 -0.57677292
  -0.57234647]]

In [43]:
# export all encoders 

with open('label_encode_gender.pkl','wb') as file:
    pickle.dump(labelencode,file)

with open('onehotencode.pkl','wb') as file:
    pickle.dump(onehotencoder,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

# ANN Implementation for Regression

In [44]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [45]:
X_train.shape[1]

12

In [46]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
]
)

In [47]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [48]:
## Introduce losses and optimizers and Callbacks (Early Stopping, tensorflowcallback)

import tensorflow

loss= tensorflow.keras.losses.MeanSquaredError()
opt= tensorflow.keras.optimizers.Adam(learning_rate=0.05)

In [49]:
## callbacks
from tensorflow.keras.callbacks import TensorBoard, EarlyStopping

early_stop= EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)
import datetime
logs_dir='logs/fit/' + datetime.datetime.now().strftime('%Y%m%D-%H%M%S')
tensor_callback= TensorBoard(logs_dir, histogram_freq=2)

In [50]:
## Compile the model

model.compile(loss=loss,optimizer=opt,metrics=['mse'])

In [51]:
#model.save('model.h5')

In [52]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [53]:
## Train the model

history= model.fit(
    X_train,y_train, epochs=100,
    validation_data=(X_test,y_test),
    callbacks=[early_stop,tensor_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\ssan\Downloads\Cursor_Projects\cursor\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 1s 3ms/step - loss: 5440758784.0000 - mse: 5440758784.0000 - val_loss: 3336999168.0000 - val_mse: 3336999168.0000
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 3348555520.0000 - mse: 3348555520.0000 - val_loss: 3378040064.0000 - val_mse: 3378040064.0000
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 3337644032.0000 - mse: 3337644032.0000 - val_loss: 3383092480.0000 - val_mse: 3383092480.0000
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 3330205952.0000 - mse: 3330205952.0000 - val_loss: 3419216640.0000 - val_mse: 3419216640.0000
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 3330976000.0000 - mse: 3330976000.0000 - val_loss: 3332628736.0000 - val_mse: 3332628736.0000
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 3318380288.0000 - mse: 3318380288.0000 - val_loss: 3387499520.0000 - val_mse: 3387499520.0000
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 3310964992.0000 - mse: 3310964992.0000 - val_loss: 3349612800.0000 - val_mse: 3349612800.0000
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 3310878976.0000 - mse: 3310878976.0000 - val_loss: 3499479808.0000 - val_mse: 3499479808.0000
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 3307173632.0000 - mse: 3307173632.0000 - val_loss: 3347425024.0000 - val_mse: 3347425024.0000
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 3313702400.0000 - mse: 3313702400.0000 - val_loss: 3350203648.0000 - val_mse: 3350203648.0000

In [54]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [55]:
from tensorflow.keras.models import load_model

## load the models 
select_model= load_model('model.h5')
select_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [56]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [57]:
# load encoders
with open('onehotencode.pkl','rb') as f:
    onehotencoder_test=pickle.load(f)
onehotencoder_test

OneHotEncoder(handle_unknown='ignore')

In [58]:
test_loss, test_mse= model.evaluate(X_test,y_test)
print(f'The Value of MAE/MSE: {test_mse}')

63/63 [==============================] - 0s 2ms/step - loss: 3332628736.0000 - mse: 3332628736.0000
The Value of MAE/MSE: 3332628736.0

In [59]:
model.save('model.h5')

c:\Users\ssan\Downloads\Cursor_Projects\cursor\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [61]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [60]:
%tensorboard --logdir logs/fit/

Reusing TensorBoard on port 6006 (pid 22556), started 0:54:34 ago. (Use '!kill 22556' to kill it.)