In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y=make_classification(n_samples=1000,n_classes=2, n_clusters_per_class=1, n_features=2, n_informative=2, n_redundant=0,random_state=7)

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=7)

In [6]:
from sklearn.svm import SVR
model=SVR()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [7]:
from sklearn.metrics import r2_score, mean_absolute_error

print(f"R2: score: {r2_score(y_test,y_pred)}")
print(f"MAE: score: {mean_absolute_error(y_test,y_pred)}")

R2: score: 0.967101113988897
MAE: score: 0.06102168010571622

In [8]:
import seaborn as sns

df=sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
X=df.drop(["total_bill"], axis=1)
y=df["total_bill"]

In [10]:
X.head()

    tip     sex smoker  day    time  size
0  1.01  Female     No  Sun  Dinner     2
1  1.66    Male     No  Sun  Dinner     3
2  3.50    Male     No  Sun  Dinner     3
3  3.31    Male     No  Sun  Dinner     2
4  3.61  Female     No  Sun  Dinner     4

In [11]:
y.head()

0    16.99
1    10.34
2    21.01
3    23.68
4    24.59
Name: total_bill, dtype: float64

In [12]:
df["sex"].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [13]:
df["smoker"].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [14]:
df["time"].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [15]:
df["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [16]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tip     244 non-null    float64
 1   sex     244 non-null    category
 2   smoker  244 non-null    category
 3   day     244 non-null    category
 4   time    244 non-null    category
 5   size    244 non-null    int64
dtypes: category(4), float64(1), int64(1)
memory usage: 5.5 KB

In [20]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.30,random_state=7)

In [21]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

le1=LabelEncoder()
cat= ["sex","time","smoker"]

for i in range(len(cat)):
  X_train[cat[i]]=le1.fit_transform(X_train[cat[i]])
  X_test[cat[i]]=le1.transform(X_test[cat[i]])

In [22]:
X_train[:10]

      tip  sex  smoker   day  time  size
28   4.30    1       0   Sat     0     2
63   3.76    1       1   Sat     0     4
114  4.00    0       0   Sun     0     3
227  3.00    1       0   Sat     0     4
15   3.92    1       0   Sun     0     2
125  4.20    0       0  Thur     1     6
58   1.76    1       1   Sat     0     2
235  1.25    1       0   Sat     0     2
36   2.00    1       0   Sat     0     3
111  1.00    0       0   Sat     0     1

In [23]:
X_test[:10]

      tip  sex  smoker   day  time  size
80   3.00    1       1  Thur     1     2
129  2.18    1       0  Thur     1     3
3    3.31    1       0   Sun     0     2
184  3.00    1       1   Sun     0     2
177  2.00    1       1   Sun     0     2
145  1.50    0       0  Thur     1     2
94   3.25    0       0   Fri     0     2
88   5.85    1       0  Thur     1     2
120  2.31    1       0  Thur     1     2
50   2.50    1       0   Sun     0     2

In [25]:
cv= ColumnTransformer(transformers=[("onehot", OneHotEncoder(drop="first"),[3])], remainder="passthrough")
X_train=cv.fit_transform(X_train)

In [26]:
X_test=cv.transform(X_test)

In [31]:
from sklearn.svm import SVR
model_sv=SVR(kernel="linear")
model_sv.fit(X_train,y_train)

y_pred_sv=model_sv.predict(X_test)
from sklearn.metrics import r2_score, mean_absolute_error

print(f"R2: score: {r2_score(y_test,y_pred_sv)}")
print(f"MAE: score: {mean_absolute_error(y_test,y_pred_sv)}")

R2: score: 0.5449317818143085
MAE: score: 3.6714188526667244

## Hyper parametr tuning

In [ ]:
from sklearn.model_selection import GridSearchCV

# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3)

# fitting the model for grid search
grid.fit(X_train, y_train)

In [33]:
grid.best_params_

{'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}

In [34]:
grid_prediction=grid.predict(X_test)

from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,grid_prediction))
print(mean_absolute_error(y_test,grid_prediction))

0.5392555872571037
3.698091068350046

In [36]:
from sklearn.svm import SVR
model_sv=SVR(C=1000, gamma=0.0001, kernel='rbf')
model_sv.fit(X_train,y_train)

y_pred_sv=model_sv.predict(X_test)
from sklearn.metrics import r2_score, mean_absolute_error

print(f"R2: score: {r2_score(y_test,y_pred_sv)}")
print(f"MAE: score: {mean_absolute_error(y_test,y_pred_sv)}")

R2: score: 0.5392555872571037
MAE: score: 3.698091068350046