## EDA of Churn Data

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder


df= pd.read_csv("C:\\Users\\ssan\\Downloads\\Cursor_Projects\\Deep_Learning\\Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [2]:
## Clean up of dataset of removing unwanted rows
df=df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [3]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# convert Categorical to numerical

label_encode_gender= LabelEncoder()
encoded_gender=label_encode_gender.fit_transform(df['Gender'])
df['Gender']=encoded_gender

In [5]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [6]:
df.Gender.value_counts()

Gender
1    5457
0    4543
Name: count, dtype: int64

In [7]:
df.Geography.value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [8]:
# convert the geography column
from sklearn.preprocessing import OneHotEncoder

encoder_geo= OneHotEncoder()
encoded_geo_val= encoder_geo.fit_transform(df[['Geography']])
encoded_geo_val.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [9]:
encoder_geo.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [10]:
encoded_df=pd.DataFrame(encoded_geo_val.toarray(),columns=encoder_geo.get_feature_names_out(['Geography']))
encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [11]:
df=pd.concat([df.drop(['Geography'],axis=1),encoded_df],axis=1)

In [12]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [13]:
from sklearn.model_selection import train_test_split
X=df.drop('Exited',axis=1)
y=df['Exited']
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.20,random_state=77)

from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [14]:
X_test

array([[ 0.65794351,  0.91025899, -0.46718535, ..., -1.00727647,
        -0.57677292,  1.74719344],
       [ 0.78224209, -1.09858844,  0.86957369, ..., -1.00727647,
        -0.57677292,  1.74719344],
       [ 1.08263035,  0.91025899, -0.94459929, ...,  0.99277609,
        -0.57677292, -0.57234647],
       ...,
       [ 1.4451679 ,  0.91025899, -1.23104766, ...,  0.99277609,
        -0.57677292, -0.57234647],
       [-1.20653533,  0.91025899,  1.15602206, ..., -1.00727647,
        -0.57677292,  1.74719344],
       [-1.03044566,  0.91025899,  0.39215975, ...,  0.99277609,
        -0.57677292, -0.57234647]])

In [15]:
X_train

array([[ 1.38301861,  0.91025899, -0.37170256, ..., -1.00727647,
        -0.57677292,  1.74719344],
       [ 0.34719703, -1.09858844, -1.23104766, ...,  0.99277609,
        -0.57677292, -0.57234647],
       [-1.14438603,  0.91025899, -0.18073698, ...,  0.99277609,
        -0.57677292, -0.57234647],
       ...,
       [ 0.3886299 ,  0.91025899, -0.94459929, ...,  0.99277609,
        -0.57677292, -0.57234647],
       [ 0.53364492,  0.91025899,  0.58312533, ...,  0.99277609,
        -0.57677292, -0.57234647],
       [-2.03519259,  0.91025899, -0.46718535, ...,  0.99277609,
        -0.57677292, -0.57234647]])

In [16]:
import pickle

# export all encoders 

with open('label_encode_gender.pkl','wb') as file:
    pickle.dump(label_encode_gender,file)

with open('onehotencode.pkl','wb') as file:
    pickle.dump(encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Implementation

In [33]:
import tensorflow 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import datetime

In [ ]:
## Create a model

model= Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
    ]
)

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 64)                832

 dense_17 (Dense)            (None, 32)                2080

 dense_18 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [39]:
# model compile to proceed with forward and backward propagation

import tensorflow
loss= tensorflow.keras.losses.BinaryCrossentropy()
opt= tensorflow.keras.optimizers.Adam(learning_rate=0.1)

model.compile(optimizer=opt, loss=loss,metrics=['accuracy'])

In [57]:
## add Early stopping
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
early_stop_callback= EarlyStopping(monitor='val_loss',patience=10, restore_best_weights=True)

## create a logs folder

logs_dir= 'logs/fit/' + datetime.datetime.now().strftime("%Y%m%D-%H%M%S")
tensor_board= TensorBoard(logs_dir,histogram_freq=2)

In [58]:
# Train the model
model.fit(X_train,y_train, validation_data=(X_test,y_test),epochs=100, callbacks=[early_stop_callback,tensor_board])

Epoch 1/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3880 - accuracy: 0.8389 - val_loss: 0.3863 - val_accuracy: 0.8370
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3788 - accuracy: 0.8465 - val_loss: 0.3769 - val_accuracy: 0.8580
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4040 - accuracy: 0.8365 - val_loss: 0.4253 - val_accuracy: 0.8150
Epoch 4/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4100 - accuracy: 0.8177 - val_loss: 0.3902 - val_accuracy: 0.8445
Epoch 5/100
250/250 [==============================] - 2s 10ms/step - loss: 0.3950 - accuracy: 0.8421 - val_loss: 0.4036 - val_accuracy: 0.8205
Epoch 6/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3788 - accuracy: 0.8466 - val_loss: 0.4221 - val_accuracy: 0.8100
Epoch 7/100
250/250 [==============================] - 2s 10ms/step - loss: 0.3733 - accuracy: 0.8511 - val_loss: 0.3633 - val_accuracy: 0.8530
Epoch 8/100
250/250 [==============================] - 3s 11ms/step - loss: 0.3753 - accuracy: 0.8456 - val_loss: 0.3625 - val_accuracy: 0.8580
Epoch 9/100
250/250 [==============================] - 4s 15ms/step - loss: 0.3721 - accuracy: 0.8493 - val_loss: 0.3524 - val_accuracy: 0.8635
Epoch 10/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3660 - accuracy: 0.8515 - val_loss: 0.3713 - val_accuracy: 0.8650
Epoch 11/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3645 - accuracy: 0.8515 - val_loss: 0.3502 - val_accuracy: 0.8615
Epoch 12/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3715 - accuracy: 0.8469 - val_loss: 0.3573 - val_accuracy: 0.8580
Epoch 13/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3687 - accuracy: 0.8520 - val_loss: 0.3569 - val_accuracy: 0.8535
Epoch 14/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3636 - accuracy: 0.8508 - val_loss: 0.3585 - val_accuracy: 0.8530
Epoch 15/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3733 - accuracy: 0.8499 - val_loss: 0.3557 - val_accuracy: 0.8555
Epoch 16/100
250/250 [==============================] - 2s 10ms/step - loss: 0.3687 - accuracy: 0.8485 - val_loss: 0.3631 - val_accuracy: 0.8495
Epoch 17/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3638 - accuracy: 0.8539 - val_loss: 0.3494 - val_accuracy: 0.8600
Epoch 18/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3662 - accuracy: 0.8535 - val_loss: 0.3644 - val_accuracy: 0.8620
Epoch 19/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4188 - accuracy: 0.8179 - val_loss: 0.4208 - val_accuracy: 0.8000
Epoch 20/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4090 - accuracy: 0.8217 - val_loss: 0.4337 - val_accuracy: 0.8000
Epoch 21/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3777 - accuracy: 0.8451 - val_loss: 0.3617 - val_accuracy: 0.8520
Epoch 22/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3697 - accuracy: 0.8490 - val_loss: 0.4215 - val_accuracy: 0.8130
Epoch 23/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3712 - accuracy: 0.8493 - val_loss: 0.3501 - val_accuracy: 0.8610
Epoch 24/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3669 - accuracy: 0.8521 - val_loss: 0.3606 - val_accuracy: 0.8595
Epoch 25/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3729 - accuracy: 0.8539 - val_loss: 0.3549 - val_accuracy: 0.8565
Epoch 26/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3653 - accuracy: 0.8520 - val_loss: 0.3533 - val_accuracy: 0.8600
Epoch 27/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3617 - accuracy: 0.8561 - val_loss: 0.3572 - val_accuracy: 0.8500

In [59]:
model.save('final_model.h5')

c:\Users\ssan\Downloads\Cursor_Projects\cursor\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [62]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [63]:
%tensorboard --logdir logs/fit/

Reusing TensorBoard on port 6006 (pid 15352), started 0:02:04 ago. (Use '!kill 15352' to kill it.)